### ISSUE TITLE
几个问题和建议

### ISSUE THREAD

**Issue by skating507** [4013465w/Wordpress-Mobile-Application#3]
1，侧边菜单容易在列表上下滑动时候弹出来；
2，分类改成自己的时候出错，获取不了数据；
3，是否可以添加一个底部选择菜单。

**Comment by aOrz** [comment]
分类改成自己的时候出错：是不是你把分类的ID填错了

**Comment by aOrz** [comment]
1,侧边菜单容易在列表上下滑动时候弹出来；
  在监听到左滑事件时会打开菜单，在list.html 21行
`//主界面向右滑动，若菜单未显示，则显示菜单；否则不做任何操作
                window.addEventListener("swiperight", openMenu);`
注释掉即可。

**Comment by skating507** [comment]
没有填错，不知道为什么，只有一个可以获取而已

**Comment by aOrz** [comment]
底部菜单完成

**Comment by skating507** [comment]
赞👍
